name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Hugo
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.143.1/hugo_extended_0.143.1_linux-amd64.deb
          sudo dpkg -i hugo.deb

      - name: Print current working directory
        run: |
          echo "Current working directory:"
          pwd

      - name: List all files in the directory
        run: |
          echo "Listing all files:"
          find . -type f

      - name: Build Hugo site
        run: hugo --gc --minify 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-pages-artifact@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
