name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is not 'main'

permissions:
  contents: read
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Hugo
      run: |
        wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.143.1/hugo_extended_0.143.1_linux-amd64.deb \
        && sudo dpkg -i hugo.deb

    - name: Print current working directory
      run: |
        echo "Current working directory:"
        pwd

    - name: List all files in the directory
      run: |
        echo "Listing all files:"
        find . -type f

    - name: Build Hugo site
      run: hugo --gc --minify --baseURL "${{ github.repository_owner }}.github.io"

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        publish_dir: ./public

