name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is not 'main'

permissions:
  contents: read
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Hugo
      run: |
        wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.141.0/hugo_extended_0.141.0_linux-amd64.deb \
        && sudo dpkg -i hugo.deb

    - name: Build Hugo site
      run: hugo --gc --minify --baseURL "${{ github.repository_owner }}.github.io"

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        publish_dir: ./public
